#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00
#PBS -m e
#PBS -M chengfeiwang.aka.chance@gmail.com
#PBS -o ./reconstruct/parameter_0800/std.log 
#PBS -e ./reconstruct/parameter_0800/err.log 
cd ~/sparse_representation/test_val_1k
echo 0800;
for each in ./resize/*; do
    output_filename=$(basename $each);
    ~/go/bin/primitive -i $each -o reconstruct/parameter_0800/$output_filename -n 800 -s 299;
done
