#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00
#PBS -m e
#PBS -M chengfeiwang.aka.chance@gmail.com
#PBS -o ./reconstruct/parameter_${n}/std.log 
#PBS -e ./reconstruct/parameter_${n}/err.log 
cd ~/sparse_representation/test_val_1k
echo ${n};
for each in ./resize/*; do
    output_filename=$(basename $each);
    ~/go/bin/primitive -i $each -o reconstruct/parameter_${n}/$output_filename -n ${n} -s 299;
done
